set nocompatible

let $BASE_DIR = expand('~/.vim')
const s:dpp_base = expand("~/.cache/dpp")
const s:dpp_src = expand("~/.cache/dpp/repos/github.com/Shougo/dpp.vim")
const s:ext_toml = expand("~/.cache/dpp/repos/github.com/Shougo/dpp-ext-toml")
const s:ext_lazy = expand("~/.cache/dpp/repos/github.com/Shougo/dpp-ext-lazy")
const s:ext_installer = expand("~/.cache/dpp/repos/github.com/Shougo/dpp-ext-installer")
const s:ext_git = expand("~/.cache/dpp/repos/github.com/Shougo/dpp-protocol-git")
const s:denops_src = expand("~/.cache/dpp/repos/github.com/vim-denops/denops.vim")
const s:dpp_config = expand("~/.vim/dpp/config.ts")

execute 'set runtimepath^=' .. s:dpp_src

execute 'set runtimepath+=' .. s:ext_toml
execute 'set runtimepath+=' .. s:ext_git
execute 'set runtimepath+=' .. s:ext_lazy
execute 'set runtimepath+=' .. s:ext_installer

execute 'set runtimepath+=' .. $BASE_DIR

if dpp#min#load_state(s:dpp_base)
    execute 'set runtimepath^=' .. s:denops_src
	autocmd User DenopsReady call dpp#make_state(s:dpp_base, s:dpp_config)
endif

exec "source " . $BASE_DIR . "/plugs/startup/startup.vim"

au QuickfixCmdPost make,grep,vimgrep,grepadd copen

" default
set title
set number
set clipboard=unnamedplus
syntax enable
set expandtab
set tabstop=4
set shiftwidth=4
set foldmethod=indent
set completeopt=menuone,noinsert
set encoding=utf-8
set hidden
set updatetime=300
set shortmess+=c

filetype plugin indent on

if has('nvim')
    " set cmdheight=0
    set laststatus=0
else
    " 挿入モード時に非点滅の縦棒タイプのカーソル
    let &t_SI .= "\e[6 q"
    " ノーマルモード時に非点滅のブロックタイプのカーソル
    let &t_EI .= "\e[2 q"
    " 置換モード時に非点滅の下線タイプのカーソル
    let &t_SR .= "\e[4 q"
    set noshowmode
endif

" popup color
hi Pmenu ctermbg=black ctermfg=white
hi PmenuSel ctermbg=yellow ctermfg=black
hi PmenuSbar ctermbg=black
hi PmenuThumb ctermfg=gray
