[[plugins]]
repo = 'matsui54/denops-popup-preview.vim'
depends = ['denops.vim']

[[plugins]]
repo = 'matsui54/denops-signature_help'
depends = ['denops.vim']

[[plugins]] 
repo = 'Shougo/ddc.vim'
depends = ['denops.vim', 'denops-popup-preview.vim']
on_event = ['BufEnter']
hooks_file = ['$BASE_DIR/plugs/ddc/ddc.vim']

[[plugins]]
repo = 'Shougo/ddc-source-around'
on_event = ['BufNew', 'BufNewFile']
on_source = 'ddc.vim'

[[plugins]]
repo = 'LumaKernel/ddc-source-file'
on_event = ['BufNew', 'BufNewFile']
on_source = 'ddc.vim'

[[plugins]]
repo = 'tani/ddc-path'
on_event = ['BufNew', 'BufNewFile']
on_source = 'ddc.vim'

[[plugins]]
repo = 'matsui54/ddc-buffer'
on_event = ['BufNew', 'BufNewFile']
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-source-cmdline'
on_event = ['BufNew', 'BufNewFile']
on_source = ['ddc.vim']
hooks_file = ['$BASE_DIR/plugs/ddc/cmdline.vim']

[[plugins]]
repo = 'Shougo/ddc-source-cmdline_history'
on_event = ['BufNew', 'BufNewFile']
on_source = 'ddc-source-cmdline'

[[plugins]]
repo = 'Shougo/ddc-source-omni'
on_event = ['BufNew', 'BufNewFile']
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-source-line'
on_event = ['BufNew', 'BufNewFile']
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-source-input'
on_event = ['BufNew', 'BufNewFile']
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-source-rg'
on_event = ['BufNew', 'BufNewFile']
on_source = 'ddc.vim'

[[plugins]]
repo = 'hrsh7th/vim-vsnip'
on_event = ['BufNew', 'BufNewFile']
on_source = 'ddc.vim'

[[plugins]]
repo = 'uga-rosa/ddc-source-vsnip'
on_event = ['BufNew', 'BufNewFile']
on_source = 'vim-vsnip'
hooks_file = ['$BASE_DIR/plugs/ddc/vsnip.vim']

[[plugins]]
repo = 'Shougo/ddc-ui-native'
on_event = ['BufNew', 'BufNewFile']
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-ui-pum'
on_event = ['BufNew', 'BufNewFile']
on_source = 'ddc.vim'

[[plugins]]
repo = 'tani/ddc-fuzzy'
on_event = ['BufNew', 'BufNewFile']
on_source = 'ddc.vim'

[[plugins]]
repo = 'matsui54/ddc-filter_editdistance'
on_event = ['BufNew', 'BufNewFile']
on_source = 'ddc.vim'
    
[[plugins]]
repo = 'Shougo/ddc-converter_remove_overlap'
on_event = ['BufNew', 'BufNewFile']
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-sorter_rank'
on_event = ['BufNew', 'BufNewFile']
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-matcher_head'
on_event = ['BufNew', 'BufNewFile']
on_source = 'ddc.vim'

[[plugins]]
repo = 'vim-skk/skkeleton'
depends = 'denops.vim'
on_event = ['BufNew', 'BufNewFile']
hooks_file = ['$BASE_DIR/plugs/ddc/skkeleton.vim']

# [[plugins]]
# repo = 'prabirshrestha/vim-lsp'
# on_source =  'ddc.vim'
# hooks_file = ['$BASE_DIR/available/ddc/vim-lsp.vim']
