[[plugins]] 
repo = 'Shougo/ddt.vim'
depends = ['denops.vim']
on_event = ['BufEnter']
hooks_file = ['$BASE_DIR/plugs/ddt/ddt-start.vim']

[[plugins]] 
repo = 'Shougo/ddt-ui-terminal'
depends = ['denops.vim', 'ddt.vim']
on_source = 'ddt.vim'
hooks_file = ['$BASE_DIR/plugs/ddt/ddt-patch_local.vim']
