[[plugins]]
repo = 'lervag/vimtex'
on_ft = 'tex'
# on_source = ['ddc.vim']

[[plugins]]
repo='kat0h/bufpreview.vim' 
depends = ['denops.vim']
on_event = ['CmdlineEnter']

[[plugins]]
repo = 'flow6852/vim-markdownUtil'
on_ft ='markdown'
