[[plugins]]
repo='flow6852/ddu-fully_understand' 
depends = ['denops.vim', 'ddu.vim']
on_source = 'ddu.vim'

[[plugins]]
repo='flow6852/dps-atcoder-facilitator' 
depends = ['denops.vim', 'ddu.vim']
on_ft = "rust"

[[plugins]]
repo = 'lervag/vimtex'
on_ft = 'tex'
on_source = ['ddc.vim']
