[[plugins]]
repo = 'neovim/nvim-lspconfig'
on_source = ['ddc.vim']
hooks_file = ['$BASE_DIR/plugs/ddc/nvim-lspconfig.vim']
on_ft = ['typescript', 'ps1', 'powershell', 'rust']

[[plugins]]
repo = 'Shougo/ddc-source-lsp'
on_source = ['ddc.vim', 'nvim-lspconfig']

# [[plugins]]
# repo = 'williamboman/mason-lspconfig.nvim'
# depends = 'nvim-lspconfig'
# 
# [[plugins]]
# repo = 'williamboman/mason.nvim'
# depends = 'mason-lspconfig.nvim'
# on_event = ['InsertEnter', 'CmdlineEnter']
# lua_source = '''
# require('mason').setup()
# require('mason-lspconfig').setup()
# require('mason-lspconfig').setup_handlers({ function(server_name)
#     require('lspconfig')[server_name].setup{on_attach = on_attach, capabilities = vim.lsp.protocol.make_client_capabilities()}
# end })
# '''
