[[plugins]] 
repo = 'Shougo/ddc.vim'
depends = ['denops.vim']
on_event = ['BufEnter']
hooks_file = ['$BASE_DIR/plugs/ddc/vime.vim']

[[plugins]]
repo = 'Shougo/ddc-source-around'
on_event = ['BufNew']
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-source-cmdline'
on_event = ['BufNew']
on_source = ['ddc.vim']
hooks_file = ['$BASE_DIR/plugs/ddc/cmdline.vim']

[[plugins]]
repo = 'Shougo/ddc-source-cmdline-history'
on_event = ['BufNew']
on_source = 'ddc-source-cmdline'

[[plugins]]
repo = 'Shougo/ddc-ui-native'
on_event = ['BufNew']
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-ui-pum'
on_event = ['BufNew']
on_source = 'ddc.vim'

[[plugins]]
repo = 'matsui54/ddc-filter_editdistance'
on_event = ['BufNew']
on_source = 'ddc.vim'
    
[[plugins]]
repo = 'Shougo/ddc-converter_remove_overlap'
on_event = ['BufNew']
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-sorter_rank'
on_event = ['BufNew']
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-matcher_head'
on_event = ['BufNew']
on_source = 'ddc.vim'

[[plugins]]
repo = 'vim-skk/skkeleton'
depends = 'denops.vim'
on_event = ['BufNew']
hooks_file = ['$BASE_DIR/plugs/ddc/skkeleton.vim']

# [[plugins]]
# repo = 'prabirshrestha/vim-lsp'
# on_source =  'ddc.vim'
# hooks_file = ['$BASE_DIR/available/ddc/vim-lsp.vim']
