[[plugins]]
repo = 'Shougo/pum.vim'

[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo =  'flow6852/dps-mergeqf'
depends = ['denops.vim']

[[plugins]]
repo =  'flow6852/dps-taskrunner'
depends = ['denops.vim']

[[plugins]]
repo='kat0h/bufpreview.vim' 
depends = ['denops.vim']
on_ft = 'markdown'
