[[plugins]]
repo = 'lervag/vimtex'
on_ft = 'tex'
# on_source = ['ddc.vim']

[[plugins]]
repo = 'mattn/vim-maketable'
on_ft = ['csv', 'markdown']

[[plugins]]
repo='kat0h/bufpreview.vim' 
depends = ['denops.vim']
on_event = ['CmdlineEnter']
hook_source = '''

'''
