[[plugins]]
repo = 'matsui54/denops-popup-preview.vim'
depends = ['denops.vim']

[[plugins]]
repo = 'matsui54/denops-signature_help'
depends = ['denops.vim']

[[plugins]]
repo = 'Shougo/ddc.vim'
depends = ['denops.vim', 'pum.vim', 'denops-popup-preview.vim', 'denops-signature_help']
on_event = ['InsertEnter']

[[plugins]]
repo = 'Shougo/ddc-source-around'
depends = ['denops.vim', 'ddc.vim']
on_source = 'ddc.vim'

[[plugins]]
repo = 'LumaKernel/ddc-source-file'
depends = ['denops.vim', 'ddc.vim']
on_source = 'ddc.vim'

[[plugins]]
repo = 'tani/ddc-path'
depends = ['denops.vim', 'ddc.vim']
on_source = 'ddc.vim'

[[plugins]]
repo = 'matsui54/ddc-buffer'
depends = ['denops.vim', 'ddc.vim']
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-source-cmdline'
depends = ['denops.vim', 'ddc.vim']
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-source-cmdline-history'
depends = ['denops.vim', 'ddc.vim']
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-source-omni'
depends = ['denops.vim', 'ddc.vim']
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-source-line'
depends = ['denops.vim', 'ddc.vim']
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-source-input'
depends = ['denops.vim', 'ddc.vim']
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-source-rg'
depends = ['denops.vim', 'ddc.vim']
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-nvim-lsp'
depends = ['denops.vim', 'ddc.vim']
on_source = ['ddc.vim']

[[plugins]]
repo = 'vim-skk/skkeleton'
depends = ['denops.vim']
on_event = ['InsertEnter']

[[plugins]]
repo = 'hrsh7th/vim-vsnip'

[[plugins]]
repo = 'hrsh7th/vim-vsnip-integ'
depends = ['vim-vsnip', 'denops.vim', 'ddc.vim']
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-ui-native'
depends = ['denops.vim', 'ddc.vim']
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-ui-pum'
depends = ['denops.vim', 'ddc.vim']
on_source = 'ddc.vim'

[[plugins]]
repo = 'tani/ddc-fuzzy'
depends = ['denops.vim', 'ddc.vim']
on_source = 'ddc.vim'

[[plugins]]
repo = 'matsui54/ddc-filter_editdistance'
depends = ['denops.vim', 'ddc.vim']
on_source = 'ddc.vim'
    
[[plugins]]
repo = 'Shougo/ddc-converter_remove_overlap'
depends = ['denops.vim', 'ddc.vim']
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-sorter_rank'
depends = ['denops.vim', 'ddc.vim']
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-matcher_head'
depends = ['denops.vim', 'ddc.vim']
on_source = 'ddc.vim'

hooks_file = '$BASE_DIR/available/ddc/ddc.vim'
