[[plugins]]
repo = 'neovim/nvim-lspconfig'
lua_source = '''
local capabilities = vim.lsp.protocol.make_client_capabilities()
capabilities.textDocument.completion.completionItem.snippetSupport = true

require('lspconfig').denols.setup{}

vim.lsp.handlers["textDocument/publishDiagnostics"] = vim.lsp.with(
    vim.lsp.diagnostic.on_publish_diagnostics, { virtual_text = false }
)

vim.api.nvim_create_autocmd('FileWritePost', {
  callback = function() vim.diagnostic.setqflist({open=false}) end
})
'''

[[plugins]]
repo = 'williamboman/mason-lspconfig.nvim'
depends = 'nvim-lspconfig'

[[plugins]]
repo = 'williamboman/mason.nvim'
depends = 'mason-lspconfig.nvim'
on_event = ['BufRead']
lua_source = '''
require('mason').setup()
require('mason-lspconfig').setup()
require('mason-lspconfig').setup_handlers({ function(server_name)
    require('lspconfig')[server_name].setup{on_attach = on_attach, capabilities = vim.lsp.protocol.make_client_capabilities()}
end })
'''

